export default {
  login: "helewrer3",
  id: 14030836,
  node_id: "MDQ6VXNlcjE0MDMwODM2",
  avatar_url: "https://avatars.githubusercontent.com/u/14030836?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/helewrer3",
  html_url: "https://github.com/helewrer3",
  followers_url: "https://api.github.com/users/helewrer3/followers",
  following_url: "https://api.github.com/users/helewrer3/following{/other_user}",
  gists_url: "https://api.github.com/users/helewrer3/gists{/gist_id}",
  starred_url: "https://api.github.com/users/helewrer3/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/helewrer3/subscriptions",
  organizations_url: "https://api.github.com/users/helewrer3/orgs",
  repos_url: "https://api.github.com/users/helewrer3/repos",
  events_url: "https://api.github.com/users/helewrer3/events{/privacy}",
  received_events_url: "https://api.github.com/users/helewrer3/received_events",
  type: "User",
  site_admin: false,
  name: "helewrer3",
  company: null,
  blog: "https://helewrer3.github.io/",
  location: "Where the wind blows, water flows, and humans clone",
  email: null,
  hireable: null,
  bio: "A college student, enjoying life!",
  twitter_username: null,
  public_repos: 26,
  public_gists: 0,
  followers: 17,
  following: 2,
  created_at: "2015-08-29T15:00:36Z",
  updated_at: "2021-02-11T11:58:27Z"
}